language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jungyu333/elasticsearch -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jungyu333/elasticsearch npm run test -- --coverage

after_success:
  - docker build -t jungyu333/docker-client ./client
  - docker build -t jungyu333/docker-server ./server
  - docker build -t jungyu333/docker-nginx  ./nginx
  - docker build -t jungyu333/docker-elasticsearch  ./elasticsearch

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jungyu333/docker-client
  - docker push jungyu333/docker-server
  - docker push jungyu333/docker-nginx
  - docker push jungyu333/docker-elasticsearch

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "elasticsearch"
  env: "Elasticsearch-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-506770882334
  bucket_path: "elasticsearch"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
