version: "3"
services:
  app_client:
    image: jungyu333/docker-frontend
    container_name: app_client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    depends_on:
      - app_server
      - app_client
    restart: always
    image: jungyu333/docker-nginx
    ports:
      - "80:80"

  app_server:
    image: jungyu333/docker-backend
    container_name: app_server
    links:
      - elasticsearch
    volumes:
      - /app/node_modules
      - ./server:/app
    mem_limit: 128m

  elasticsearch:
  init: true
  container_name: elasticsearch
  expose:
    - "9200"
  build:
    context: elasticsearch/
    args:
      ELK_VERSION: ${ELK_VERSION}
  volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z

  ports:
    - "9200:9200"
    - "9300:9300"

  environment:
    ES_JAVA_OPTS: -Xms256m -Xmx256m
    discovery.type: single-node
