version: "3"
services:
  app_client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: app_client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  nginx:
    depends_on:
      - app_server
      - app_client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  app_server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: app_server
    links:
      - elasticsearch
    volumes:
      - /app/node_modules
      - ./server:/app

  elasticsearch:
    init: true
    container_name: elasticsearch
    expose:
      - "9200"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
