version: "3"
services:
  app_client:
    image: jungyu333/docker-client
    container_name: app_client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: jungyu333/docker-nginx
    ports:
      - "80:80"

  app_server:
    image: jungyu333/docker-server
    container_name: app_server
    links:
      - elasticsearch
    volumes:
      - /app/node_modules
      - ./server:/app
    mem_limit: 128m

  elasticsearch:
    init: true
    image: jungyu333/docker-elasticsearch
    container_name: elasticsearch
    expose:
      - "9200"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - "9200:9200"

    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
